### ISSUE TITLE
Accessing tuples with dot syntax is not supported

### ISSUE THREAD

**Issue by stergiotis** [AfterShip/clickhouse-sql-parser#113]
In ClickHouse Tuple values may be accessed by using dot notation:
```
SELECT tuple('a','b','c').3 --> 'c'
```
further tuple elements can have names and accessed by the name. A more elaborate example:
```
SELECT toTypeName( tuple('a' as first,'b' as second ,'c' as third)::Tuple(first String,second String,third String)),
       (tuple('a' as first,'b' as second ,'c' as third)::Tuple(first String,second String,third String)).second,
       tuple('a','b','c').3,
       tupleElement(tuple('a','b','c'),1)
```
It would IMHO improve this library if it would support the tuple dot notation.

**Comment by git-hulk** [comment]
@stergiotis Thanks for your report.

> It would IMHO improve this library if it would support the tuple dot notation.

And yes, we would like to support the full set of ClickHouse syntaxes, so it should be supported if it's valid to ClickHouse. Will support it soon.
