### ISSUE TITLE
Add the support of CREATE FUNCTION 

### ISSUE THREAD

**Issue by orginux** [AfterShip/clickhouse-sql-parser#14]
file `create-function.sql`:
```sql
CREATE FUNCTION linear_equation AS (x, k, b) -> k*x + b;
```

```bash
clickhouse-sql-parser -format -f  create-function.sql
```
output:
```bash
panic: parse statements error: line 0:7 <EOF> or ';' was expected, but got: "FUNCTION"
CREATE FUNCTION linear_equation AS (x, k, b) -> k*x + b;
       ^^^^^^^^
```
[UDF in ClickHouse documentation ](https://clickhouse.com/docs/en/sql-reference/statements/create/function)

**Comment by git-hulk** [comment]
Hi @orginux Thanks for your feedback!

It's right we now don't support creating UDF, I will submit a patch for this later.

**Comment by orginux** [comment]
Great, thanks a lot @git-hulk
