### ISSUE TITLE
Add the support of CREATE ROLE

### ISSUE THREAD

**Issue by orginux** [AfterShip/clickhouse-sql-parser#16]
Similar to #14 but about CREATE ROLE

```sql
CREATE ROLE IF NOT EXISTS team_1;
```

```bash
clickhouse-sql-parser -f create-role.sql
```
output:
```bash
panic: parse statements error: line 0:7 expected keyword: DATABASE|TABLE|VIEW|DICTIONARY|FUNCTION|ROW|QUOTA|SETTINGS, but got "ROLE"
CREATE ROLE IF NOT EXISTS team_1;
       ^^^^
```

**Comment by git-hulk** [comment]
@orginux Thanks for your feedback, will support it soon.

**Comment by orginux** [comment]
@git-hulk thank you and as far as I see the same for GRANT
https://clickhouse.com/docs/en/sql-reference/statements/grant#granting-privilege-syntax

**Comment by git-hulk** [comment]
> @git-hulk thank you and as far as I see the same for GRANT https://clickhouse.com/docs/en/sql-reference/statements/grant#granting-privilege-syntax

Let's track it on #18
