### ISSUE TITLE
Will there be support for generating SQL from AST in the future?

### ISSUE THREAD

**Issue by hungtcs** [AfterShip/clickhouse-sql-parser#36]
I found a library in the go ecosystem that generates sql from ast, but it's for postgres databases, so if clickhouse had a similar library, it would be especially useful for sql analysis!

- https://github.com/pganalyze/pg_query_go

**Comment by git-hulk** [comment]
Hi @hungtcs, thanks for your proposal.

> I found a library in the go ecosystem that generates sql from last

Want to know where's the AST generated from? if it's supported now if the AST is generated by clickhouse-sql-parser.

**Comment by hungtcs** [comment]
Hi @git-hulk , Thanks for the heads up, I tried modifying the AST and calling its String method and it worked, great, that's exactly the functionality I was looking for  ! 

This is a very important feature, and I suggest we should explicitly state it in the README in case someone like me doesn't find this treasure!

**Comment by git-hulk** [comment]
@hungtcs Sure, thank you!
