### ISSUE TITLE
Clickhouse sql syntax compatibility report

### ISSUE THREAD

**Issue by hungtcs** [AfterShip/clickhouse-sql-parser#37]
Hi, 
I'm currently testing how well clickhouse-sql-parser matches the Clickhouse SQL syntax to avoid a situation where it works in clickhouse-cli but the parser parses it with an error.
This work is currently ongoing, but here I am, instantly documenting what I've discovered. I hope this helps with the optimization of this library.

I'm using Clickhouse on `24.1.1.2048`.

---

## Table Name

I've found some characters that report errors in parser, but work fine in clickhouse-cli.

1. The table name cannot contain the `$` character, but in cli you can.

    ```sql
    with $abc as (select 1 as a) select * from $abc
    ```
    ```
    SQL Parse Failed: line 0:5 unexpected token kind: $ with $abc as (select 1 as a) select * from $abc ^
    ```
2. Table names cannot be wrapped in double quotes, but they can be in clickhouse-cli.

    ```sql
    with "abc" as (select 1 as a) select * from "abc"
    ```
    ```
    SQL Parse Failed: line 0:45 expected table name or subquery, 
    got &{45 48 <string> abc 0 false} with "abc" as (select 1 as a) select * from "abc" ^^^
    ```

---

## Join 

It seems that the join syntax is not supported, here is a simple test

```sql
with t1 as ( select 1 as value ), t2 as ( select 2 as value ) select * from t1 left join t2 on true
```

```
line 0:84 <EOF> or ';' was expected, but got: "join"
with t1 as ( select 1 as value ), t2 as ( select 2 as value ) select * from t1 left join t2 on true
```

---

To be continued.

**Comment by git-hulk** [comment]
@hungtcs Thanks for your reports and samples. Will take a look and fix it soon.

**Comment by git-hulk** [comment]
@hungtcs All issues are resolved in the master branch, welcome to have a try. Feel free to open another issue to report if you have any further issues.

**Comment by hungtcs** [comment]
Thanks @git-hulk , 
I have confirmed that all the above issues have been fixed. 
But I found a new problem with join, the following sql is not parsed correctly, I omitted the `inner` keyword of `inner join`:

```sql
select * from "t1" join "t2" on true
```
```
line 0:19 <EOF> or ';' was expected, but got: "join"
select * from "t1" join "t2" on true
                   ^^^^
```

**Comment by git-hulk** [comment]
@hungtcs Thank you! Will fix this soon.

**Comment by git-hulk** [comment]
@hungtcs Can have a try at the master branch again.

**Comment by hungtcs** [comment]
Thanks @git-hulk  , now the join syntax works perfectly 🎉
