### ISSUE TITLE
[Syntax Compatibility] TableIdentifier does not support double quotes

### ISSUE THREAD

**Issue by hungtcs** [AfterShip/clickhouse-sql-parser#46]
The following SQL can be executed in clickhouse-cli, but is not parsed correctly

```
panic: line 0:43 <EOF> or ';' was expected, but got: "."
select table_name from "information_schema"."tables" limit 1
                                           ^
```

<img width="571" alt="image" src="https://github.com/AfterShip/clickhouse-sql-parser/assets/11692935/1acf0f57-df8d-4a0c-b740-5e3888879700">

Note that TableIdentifier supports double quotes, but not single quotes.

```sql
select table_name from "tables" limit 1 -- valid
select table_name from 'tables' limit 1 -- single quotes is valid
select table_name from information_schema.tables limit 1 -- valid
select table_name from "information_schema"."tables" limit 1 -- valid
select table_name from information_schema."tables" limit 1 -- valid
select table_name from "information_schema".tables limit 1 -- valid

select table_name from 'information_schema'.'tables' limit 1 -- !!! single quotes is invalid
select table_name from 'information_schema'.tables limit 1 -- !!! single quotes is invalid
select table_name from information_schema.'tables' limit 1 -- !!! single quotes is invalid
```

**Comment by hungtcs** [comment]
And by the way, the following code outputs better compatibility using double quotes.

```go
var query = `select table_name from "tables" limit 1`
var parser = clickhouse.NewParser(query)
var exprs, _ = parser.ParseStatements()
var expr = exprs[0]
fmt.Printf("%v\n", expr.String(0))
```

Outputs:

```sql
SELECT 
  table_name
FROM
  'tables' -- It's better to use double quotes
LIMIT 1
```

----

Additionally `expr.String(0)`, the value `0` for the parameter `level` seems to have no effect.

----

Thanks.

**Comment by git-hulk** [comment]
@hungtcs Thanks for your feedback. Will fix them in the future, PR is also welcomed.

**Comment by git-hulk** [comment]
@hungtcs All your reports are resolved now, welcome to have a try, and feel free to reopen if you find anything goes wrong.

**Comment by hungtcs** [comment]
Hi @git-hulk , Thanks for the timely update, I'll test it as soon as possible, with my current coding skills it's not enough to provide a PR, please forgive me, I'm actually learning how to write a parser 💪

**Comment by git-hulk** [comment]
@hungtcs Thank you! No worry about this, it's really helpful to report so many compatibility issues.
