### ISSUE TITLE
[Syntax Compatibility] Identifiers with quotes serialized output the wrong content

### ISSUE THREAD

**Issue by hungtcs** [AfterShip/clickhouse-sql-parser#53]
## Steps to Reproduction

Use the following SQL statement as a test:

```sql
select "table_name" from "information_schema"."tables" limit 1

select table_name from information_schema.tables limit 1
```

When the identifier is in quotes, the related section of the parsed AST looks like this:

```go
&parser.StringLiteral{LiteralPos:8, LiteralEnd:18, Literal:"table_name"}
&parser.ColumnExprList{ListPos:8, ListEnd:18, HasDistinct:false, Items:[]parser.Expr{(*parser.StringLiteral)(0x14000134000)}}

&parser.StringLiteral{LiteralPos:15, LiteralEnd:33, Literal:"information_schema"}
&parser.StringLiteral{LiteralPos:36, LiteralEnd:42, Literal:"tables"}
&parser.TableIdentifier{Database:(*parser.StringLiteral)(0x1400014c000), Table:(*parser.StringLiteral)(0x1400014c020)}
```

The parsed AST, when unquoted, looks like this:

```go
&parser.Ident{Name:"table_name", Unquoted:false, NamePos:7, NameEnd:17}
&parser.ColumnExprList{ListPos:7, ListEnd:17, HasDistinct:false, Items:[]parser.Expr{(*parser.Ident)(0x1400010e150)}}

&parser.Ident{Name:"information_schema", Unquoted:false, NamePos:14, NameEnd:32}
&parser.Ident{Name:"tables", Unquoted:false, NamePos:33, NameEnd:39}
&parser.TableIdentifier{Database:(*parser.Ident)(0x1400010e180), Table:(*parser.Ident)(0x1400010e1b0)}
```

For each of the two cases above,  the output in the first case is incorrect because identifiers should be in double quotes instead of single quotes, the output is:

```sql
SELECT 'table_name' FROM 'information_schema'.'tables' LIMIT 1

SELECT  table_name FROM information_schema.tables LIMIT 1
```

## Conclusion

By looking at the differences in the ASTs above, it can be seen that when the identifier is in double quotes, __**the parser incorrectly resolves it to a StringLiteral instead of an Ident node**__, which results in an error in serialization.

---

Reference document

- <https://clickhouse.com/docs/en/sql-reference/syntax#identifiers>
- <https://clickhouse.com/docs/en/sql-reference/syntax#string>

---

Thanks.

**Comment by hungtcs** [comment]
1. It is recommended that where identifiers appear in parsing TableIdentifier or ColumnExprList, etc., the identifiers should always be parsed as Ident nodes rather than StringLiteral nodes, to ensure consistency in the AST output.
3. It is also recommended to always use double quotes or backticks to wrap identifiers when serializing, so as to avoid syntax errors caused by special characters in identifiers. Or refer to clickhouse-cli, which uses backticks to wrap identifiers when it detects special characters such as "$".

**Comment by hungtcs** [comment]
Also I found a couple of parsing errors where the following SQL could not be parsed correctly:

```sql
select
  "databases"."name" as "database_name",
  "tables"."name" as "table_name"
from
  "system"."databases"
  left join "system"."tables" on "tables"."database" = "databases"."name"
```

The section that triggered the error was

1. "databases"."name" as "database_name",
2. "tables"."database" = "databases"."name"

It looks like column identifiers don't support double quotes.

**Comment by git-hulk** [comment]
@hungtcs Cool, you're right that the string with double quotes should be regarded as an indent instead of a string.
