### ISSUE TITLE
Add the support of PROJECTION

### ISSUE THREAD

**Issue by yunnnnn1** [AfterShip/clickhouse-sql-parser#59]
clickhouse version 22.8  support PROJECTION 

example： 
ALTER TABLE visits_order ADD PROJECTION user_name_projection (SELECT  *  ORDER BY user_name )
ALTER TABLE visits_order MATERIALIZE PROJECTION user_name_projection

**Comment by git-hulk** [comment]
@yunnnnn1 it's supported now, welcome to have a try at the master branch.
