### ISSUE TITLE
Unable to parse comment lines under certain circumstances

### ISSUE THREAD

**Issue by hungtcs** [AfterShip/clickhouse-sql-parser#65]
Parsing fails when parsing two consecutive lines of comments

```sql
select
  -- first line
  -- second line
  *
from
  t0
```

```
line 2:3 unexpected token kind: -
          -- second line
           ^
```

Reproduce the issue via this link
https://goplay.tools/snippet/KzNGlNKqqII

**Comment by git-hulk** [comment]
@hungtcs Thanks for your report, will fix it soon.

**Comment by hungtcs** [comment]
Test Passed 🎉
https://goplay.tools/snippet/sO1IFoMIBBE

**Comment by git-hulk** [comment]
@hungtcs Thank you!
