### ISSUE TITLE
Table alias in FROM clause is not parsed

### ISSUE THREAD

**Issue by jakobfaerch** [AfterShip/clickhouse-sql-parser#70]
The following SQL 
```
SELECT t.Timestamp FROM my_table t
```
results in the error message
> err=line 0:33 <EOF> or ';' was expected, but got: "t"

Looking at 
https://clickhouse.com/docs/en/sql-reference/statements/select
I am not sure it's really specified as valid SQL, but ClickHouse allows it, and I see constructs like it in real world use, so it would be magnificent if the parser supported it.

**Comment by jakobfaerch** [comment]
A similar construct not accepted by the parser, which as far as I can tell _is_ valid SQL according to ClickHouse specs is
```
SELECT t1.Timestamp FROM my_table t1 INNER JOIN my_other_table t2 ON t1.a=t2.b
```

**Comment by git-hulk** [comment]
@jakobfaerch Yes, you're right that ClickHouse did support this table alias without `AS` keyword.

**Comment by jakobfaerch** [comment]
Wow, that was fast. Thanks! How often do you usually tag a new release?

**Comment by git-hulk** [comment]
@jakobfaerch The new release 0.3.4 is ready now.

**Comment by jakobfaerch** [comment]
> @jakobfaerch The new release 0.3.4 is ready now.

Great, I see it.

**Comment by jakobfaerch** [comment]
@git-hulk, it seems that the new release is labeled "v0.3.4", following the convention from earlier releases, but the git tag is "0.3.4", with no leading `v`.

It currently prevents me from upgrading, due to the stubbornness of `go mod`.
Would it be possible to add a `v0.3.4` tag to the release?

**Comment by git-hulk** [comment]
@jakobfaerch Sure, my bad for missing that.
