### ISSUE TITLE
Support parameters

### ISSUE THREAD

**Issue by jsommr** [AfterShip/clickhouse-sql-parser#92]
Thanks for an excellent library that also easily compiles to wasm.

I'm thinking about using it to help make sure all queries are isolated per tenant, by checking (with eslint) sql referencing tables with a tenant_id column if they include `where tenant_id = {tenant_id: String}`, and trigger an error if not. But parameters seems to be unsupported:
```
line 0:43 unexpected token kind:
select * from clickhouse where tenant_id = {tenant_id: String}
                                           ^
```

**Comment by git-hulk** [comment]
@jsommr Thanks for your report. Will support this when I get time and PR is always welcome.

**Comment by hungtcs** [comment]
+1, Hopefully to supporte the `?` placeholders.

**Comment by git-hulk** [comment]
@hungtcs Would you mind submit another issue to track this?

**Comment by hungtcs** [comment]
> > +1, Hopefully to supporte the `?` placeholders.
> 
> @hungtcs Would you mind submitting another issue to track this?

Okay, I'll track this in other issues.

**Comment by git-hulk** [comment]
@hungtcs 

> > > +1, Hopefully to supporte the `?` placeholders.
> > 
> > 
> > @hungtcs Would you mind submitting another issue to track this?
> 
> Okay, I'll track this in other issues.

@hungtcs This also has been resolved now, please have a try again.
