### ISSUE TITLE
Add the support for `SELECT <expr> REPLACE`

### ISSUE THREAD

**Issue by StephenSorriaux** [AfterShip/clickhouse-sql-parser#99]
Hello,

Thanks for the project.

Got this error because the `REPLACE` modifier is not handled.

```
2024/09/16 16:13:26 line 0:9 <EOF> or ';' was expected, but got: "REPLACE"
SELECT * REPLACE (1 as test) FROM some_db.some_table
         ^^^^^^^
exit status 1
```
https://clickhouse.com/docs/en/sql-reference/statements/select#replace

Probably the same issue with other modifiers.

Feel free to close if modifiers are out of scope of the project.

**Comment by git-hulk** [comment]
@StephenSorriaux Thanks for your report. Will support this soon.

**Comment by StephenSorriaux** [comment]
Amazing support. Thank you.
